### ISSUE TITLE
Showing multiple errors while activating key.

### ISSUE THREAD

**Issue by BhargavBhandari90** [rtMediaWP/transcoder#43]
If we leave the blank field for a license key and tried to hit `Save Key` multiple times, then it is showing multiple error messages.

![multiple-error](https://user-images.githubusercontent.com/19459637/34600318-e7de8f8e-f21c-11e7-9dda-2b649e712ea5.png)

**Comment by DevikVekariya** [comment]
@kirtangajjar we will close this issue after QA/Testing.

**Comment by juhi123** [comment]
@DevikVekariya It seems fixed 👍
