### ISSUE TITLE
[Customer Query] Files wont play on iPhone after transcoding

### ISSUE THREAD

**Issue by kjnanda** [rtMediaWP/transcoder#78]
I am able to reproduce the issue what the customer had mentioned with his test data file for i-devices. 

@SID177 Please look into this. I have asked for debug log to the customer. Will share that here once I will get the reply on the ticket.

Files wont play on iPhone

Please check this visual.

1. https://goo.gl/fJtq2f
2. https://goo.gl/CokhJQ

-----
**Note :** 

I also checked the same thing on the demo site `mov` file and that works fine for me for i-devices. But could not play the file on iphone x the customer shared.

**Comment by kjnanda** [comment]
@SID177 Please check this bug log info sent by the cutomer.

[https___rtmedia.io_wp-content_uploads_rtbiz-helpdesk_2019_01_debuginfo-1.txt](https://github.com/rtMediaWP/transcoder/files/2806270/https___rtmedia.io_wp-content_uploads_rtbiz-helpdesk_2019_01_debuginfo-1.txt)

**Comment by SID177** [comment]
The generated error says - ```<p>Media error: Format(s) not supported or source(s) not found</p>```
